### ISSUE TITLE
pow does not meet target

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#404]
While testing PoW with two block producers and a non producing node, a block produced by A would fail B with error "pow does not meet target", but would be accepted by A (trivially) and the non producing node.

**Comment by mvandeberg** [comment]
This behavior could have been explained by #408. Since we have a temporary solution in place, I think we can consider this resolved.

**Comment by mvandeberg** [comment]
#424 provides more details as to the cause of the issue.

**Comment by theoreticalbts** [comment]
Copied from #424:

The main way this manifests currently is with "pow does not meet target" error message.

We need to implement some sort of solution.  There are two options, which I'll call the locking implementation and the reference counting implementation.

With either approach, there are some subtle pitfalls, which I'll cover first.

### Pitfalls

Implementors we have to consider the following pitfall:

- Database has block 100, we have deltas for 101,102,103,104,105.
- Start updating irreversibility from 100 to 103.
- Start a read, the read goes back to 101 and sees it can't access 100 as DB is busy.
- The read then grabs data from the database and applies 101, 102 deltas to it, but the DB is now at 103, so it attempts to apply 101,102 deltas to 103 and gets nonsense.

To prevent this you need to lock at the beginning.

But there's another pitfall we need to consider:  Orphaned forks.

- Database has block 100, we have deltas for 101, 102a, 103a, 104a, 102b, 103b, 104b.
- Receive 105b, and start updating irreversibility from 100 to 103b.
- Reader wants to read 104a.
- When the lock releases, DB is updated to 103b.  The reader can no longer access state 104a because the ancestor is lost.

### Locking implementation

The locking implementation would basically use [std::shared_mutex](https://en.cppreference.com/w/cpp/thread/shared_mutex), readers would call `lock_shared()` while writers would call `lock()`.

I'm not sure how the locking implementation would handle orphaned nodes.  You'd have to maybe mark nodes as orphaned?

### Reference counting implementation

The reference counting implementation would avoid the above issues by only actually discarding old state when no pointers to it exist.

Effectively we'd change `_parent` in `state_delta` from a `shared_ptr` to a `weak_ptr`.  Then whenever we need to use `_parent`, we `lock()` it.  If the `lock()` fails because the object was deleted, we re-get it by querying its `_id`.  (To implement this query, each `state_node` will need a pointer to `statedb`, which should itself be a `weak_ptr` to avoid creating a cycle since `statedb` contains pointers to `state_node` in `_index`.)

Normally nodes for the whole fork history are kept alive by being referred to by `shared_ptr`'s kept in `_index`.  We can start the deletion process by removing these nodes from `_index` and putting a `weak_ptr` to the nodes into `_weak_index`.  We can get notified when the deletion process ends by having the `state_node_impl` destructor send a notification to `statedb` which tells it to delete its ID from `_weak_index`.

Once `_weak_index` is empty, we know nobody's using the state nodes, so it's safe to advance the database.
