### ISSUE TITLE
[QUESTION]: Can an attacker delete the whole database?

### ISSUE THREAD

**Issue by joticajulian** [koinos/koinos-chain#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the documentation?

- [X] I have read the documentation

### Ask a question

Let's assume that an attacker can take control of the governance system. Then he set a new system contract that makes calls to put_object in order to delete data from other contracts. Is that possible?

can he use this power to delete the history as well (blocks and transactions)?

**Comment by mvandeberg** [comment]
If an attacker can some how compromise a single node, they could do whatever they wanted to the single node, but it would not be wide spread unless the payload was delivered within a block.

Assuming the attacker takes control of governance and uploads malicious smart contracts... System contracts may only access system space. They would not be able to delete data stored in smart contracts, but could delete the contracts themselves. They could also change KOIN balances because KOIN is implemented using a system contract. Even without having access to contract data, this is a catastrophic and represents worst case scenario.

There is nothing they could do to delete blocks and/or transactions from governance. Those are stored in separate microservices and the only way that data can be deleted is by starting the microservice with the `reset` flag. In fact, the microservices are already designed to store orphaned blocks and transactions for archival purposes. 

An attacker may be able to exploit a flaw in the microservice that would allow shelling out and deleting the files in the OS. Again, the payload would need to be delivered via a block or a transaction to affect the entire network. But this along with an exploit that might allow direct access to the database would be vulnerabilities in the microservice implementations themselves, and not governance.
