### ISSUE TITLE
[QUESTION]: why arguments are not passed directly to the VM?

### ISSUE THREAD

**Issue by joticajulian** [koinos/koinos-chain#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the documentation?

- [X] I have read the documentation

### Ask a question

I was looking to the documentation of WebAssembly and I found that the standard way of defining function is using `export function`:
```
export function add(a: i32, b: i32): i32 {
  return a + b;
}
```
and then this function is the interface to interact with the compiled wasm:
```
const addResult = wasmModule.instance.exports.add(24, 24);
```
meaning that when the wasm instance is called, both name and arguments are passed to it.

This is also present in Fizzy VM. Here is an example from the documentation (https://docs.rs/fizzy/latest/fizzy/#):
```
      let result = instance
        .execute(
            "sum",
            &[fizzy::TypedValue::U32(42), fizzy::TypedValue::U32(24)],
        )
        .expect("execution failed");
```

The question is why this approach is not used in Koinos, or, if you plan to implement it in the future. This change could optimize the execution of the contracts because right now nothing is passed to the contract and then the contract has to call back the system to get the entry point and the arguments.

**Comment by theoreticalbts** [comment]
A Koinos smart contract doesn't run using an FFI-style call, like how most people use WebAssembly (including your above example).  Instead, a smart contract uses WASI and runs sort-of-like a normal program under a native OS, where the runtime does some low-level initialization stuff and then calls `main()`.  This approach seems to be the only way to enable C++ smart contracts with an off-the-shelf CRT and stdlib.  (Or at least that was the state of affairs when we started implementing the Koinos smart contract system; WebAssembly / Fizzy / the C++ ecosystem may have evolved to handle C++ better since then.)

So, the answer to your question is that what Koinos currently does is the only way we found to allow users to write smart contracts in C++ using the C++ standard library.  Which assumes a traditional runtime that e.g. does static initialization (I think something-something-crt0).  Some early experimentation showed this approach was needed to support even the most basic features of C++ (e.g. `vector<>`).
